### ISSUE TITLE
where to build the C++ examples?

### ISSUE THREAD

**Issue by carmeloevoli** [cosmicrays/hermes-examples#2]
https://github.com/cosmicrays/hermes-examples/blob/f0a5470094cab3bc938a9a42c487fffa20f9af12/cpp/CMakeLists.txt#L107

I would like to copy all .cpp files in a src/ folder, such that to build them I have to make a build/ dir in the cpp/ folder and from there run `cmake ..`

In that case, this line should be:
```
add_executable(freefree src/freefree.cpp)
```

@adundovi do you agree?

**Comment by adundovi** [comment]
OK, looks fine, but put also that inner build directory by default in `.gitignore`.

**Comment by carmeloevoli** [comment]
done!
